FROM elixir:latest

RUN apt-get update && \
  apt-get install -y postgresql-client && \
  apt-get install -y inotify-tools && \
  apt-get install -y nodejs && \
  curl -L https://npmjs.org/install.sh | sh && \
  mix local.hex --force && \
  mix archive.install hex phx_new 1.5.3 --force && \
  mix local.rebar --force

ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

RUN mkdir assets

COPY src/assets/package.json assets
COPY src/assets/package-lock.json assets
RUN cd assets && npm install && cd ..

CMD ["mix", "phx.server"]